<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FolderNotePlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LongBetterWindows.Host\LongBetterWindows.Host.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <PluginLocalization Include="i18n\*.json" />
  </ItemGroup>

  <Target Name="CopyToPlugins" AfterTargets="Build">
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\FolderNotePlugin" />
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\FolderNotePlugin\i18n" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\FolderNotePlugin" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\FolderNotePlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Plugins\FolderNotePlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\..\Plugins\FolderNotePlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\..\Plugins\FolderNotePlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\FolderNotePlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\FolderNotePlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\FolderNotePlugin\i18n" />
  </Target>

</Project>
