<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>ColorPickerPlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LongBetterWindows.PluginSdk\LongBetterWindows.PluginSdk.csproj" />
    <ProjectReference Include="..\LongBetterWindows.PluginSdk.Wpf\LongBetterWindows.PluginSdk.Wpf.csproj" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PluginLocalization Include="i18n\*.json" />
  </ItemGroup>

  <Target Name="CopyToPlugins" AfterTargets="Build">
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\ColorPickerPlugin" />
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\ColorPickerPlugin\i18n" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ColorPickerPlugin" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ColorPickerPlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Plugins\ColorPickerPlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\..\Plugins\ColorPickerPlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\..\Plugins\ColorPickerPlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ColorPickerPlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ColorPickerPlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ColorPickerPlugin\i18n" />
  </Target>

</Project>
