<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>ScreenshotPlugin</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LongBetterWindows.Host\LongBetterWindows.Host.csproj">
      <Private>false</Private><ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <PluginLocalization Include="i18n\*.json" />
  </ItemGroup>
  <Target Name="CopyToPlugins" AfterTargets="Build">
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\ScreenshotPlugin" />
    <MakeDir Directories="$(ProjectDir)..\..\Plugins\ScreenshotPlugin\i18n" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ScreenshotPlugin" />
    <MakeDir Directories="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ScreenshotPlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Plugins\ScreenshotPlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\..\Plugins\ScreenshotPlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\..\Plugins\ScreenshotPlugin\i18n" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ScreenshotPlugin" />
    <Copy SourceFiles="$(ProjectDir)manifest.json" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ScreenshotPlugin" />
    <Copy SourceFiles="@(PluginLocalization)" DestinationFolder="$(ProjectDir)..\LongBetterWindows.Host\bin\$(Configuration)\net8.0-windows\Plugins\ScreenshotPlugin\i18n" />
  </Target>
</Project>
